language: objective-c
osx_image: xcode7.2.1
sudo: false
before_install:
- pod --version
- pod setup
- pod update
script:
- pod lib lint --allow-warnings --verbose
- xcodebuild test -scheme PSCarouselViewTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1'
