language: objective-c
osx_image: xcode8

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
script:
- xcodebuild -workspace ./CarouselDemo/CarouselDemo.xcworkspace -scheme 'PSCarouselViewTests'
